### PR TITLE
After adding cluster, refresh Explorer to show it

### LINKED ISSUE #115: after configure cluster ,still need to click refresh button to get the new cluster
Repro steps:
1. click configure from Cluster
2. select the sb and the cluster you want to configure
3. wait configure complete

Expect: the new cluster appear in the cluster list
Actual: we need to manually refresh the list to see the new cluster

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #115.

### CODE REVIEW

File: src/components/clusterprovider/azure/azureclusterprovider.ts [hunk 1]
```diff
@@ -446,3 +450,7 @@ function parseCluster(encoded: string) : azure.ClusterInfo {
         name: encoded.substr(delimiterPos + 1)
     };
 }
+
+async function refreshExplorer() : Promise<void> {
```
Comment (andxu) [inline src/components/clusterprovider/azure/azureclusterprovider.ts]: remove async and replace await with return

Comment (itowlson) [reply src/components/clusterprovider/azure/azureclusterprovider.ts]: Hmm, as this is conceptually `void`, I kind of find the imperative `await` more natural than a `return` (though I know it is indeed actually returning a Promise/Thenable object rather than being truly void).  Would prefer to leave it unless you feel strongly.
