### PR TITLE
Fix kubectl versioning woes

### LINKED ISSUE #306: Inconsistent choice of kubectl executable
If a user has configured a location for the `kubectl` executable (which we do automatically if they do an Install Dependencies), _and_ there is a version of `kubectl` on the path, then we are inconsistent about which we use.  Specifically, the configured on is used for 'silent' invocations, such as when populating the tree view; but in a spawned terminal, the one on the path wins out.  This can lead to different behaviour if the two are different versions - e.g. if the configured version is far ahead of the server but the path version is in sync, then the tree view may display NotAcceptable errors which the user cannot reproduce or diagnose in the terminal.

### PR DESCRIPTION
**Pull request by itowlson**
This PR addresses two versioning issues with `kubectl`:

1. Terminals could use a different version of `kubectl` from "behind-the-scenes" calls, if the user had set a location for `kubectl` in their VS Code configuration.  This occurred because "behind-the-scenes" would directly invoke the program at the configured location, whereas terminals would append the configured location to the path (so that the user could issue follow-up commands without having to type out the configured path) -- so if `'kubectl` was _also_ on the path then the path version would take precedence.  This meant the kubectl terminal was consistent with a system terminal, but made it hard to diagnose/reproduce the behaviour of "behind-the-scenes" commands.  Terminals now _prepend_ the configured location to the path, so that the configured location takes precedence.

2. Kubernetes only guarantees compatibility with at most one minor version of skew between client and server.  For example, `kubectl get pods` in v1.11 fails with server version v1.7.  This would lead to enigmatic errors, for example when expanding the tree (an Error node and toast saying something about being Not Acceptable).  We now check `kubectl` failures and, if the versions are too far out of sync, display an additional warning to this effect.  (This may be too aggressive at the moment, e.g. might not want to warn more than once per cluster, for both performance and user annoyance reasons; but `kubectl` failures should be relatively rare and a versioning issue is likely to be non-obvious when it hits.)

Fixes #306 and #298.

### CODE REVIEW

File: src/components/kubectl/compatibility.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    if (sr.code !== 0) {
+        return {
+            guaranteed: false,
+            didCheck: false,
+            clientVersion: '',
+            serverVersion: ''
+        };
+    }
+
+    const lines = sr.stdout.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
```
Comment (bnookala) [inline src/components/kubectl/compatibility.ts]: you can use the json output from `kubectl version -o json`, if that makes life any easier here…

Comment (itowlson) [reply src/components/kubectl/compatibility.ts]: TIL! Thank you!
