### PR TITLE
Fix open dashboard on aks

### LINKED ISSUE #105: Fail to open dashboard through "open dashboard" in explorer
Right click "open dashboard" and then http://localhost:8001/ui/ is opened in my browser with error message "This website can not be reached". 

If I run below command in TERMINAL, I can successfully open the dashboard.
az aks browse -g xxx -n xxx
http://localhost:8001/ui/

### PR DESCRIPTION
**Pull request by bnookala**
Fixes #105.

Rebased #137 - which is why the commits from there are also here. If anybody is merging this, please wait until #137 is merged before merging this.

### CODE REVIEW

**Comment by bnookala** [comment]
Rebased on the changes I made to #137!

File: src/components/kubectl/dashboard.ts [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+let terminal:vscode.Terminal;
+
+/**
+ * Determines if the selected cluster is AKS or not by examining
+ * all the attached nodes for two heuristics:
+ * 1. Is every node an agent?
+ * 2. Is the node name prefixed with `aks-`? (TODO: identify if there's a better method for this/convince AKS team to add a label) for this.
+ * @returns Boolean identifying if we think this is an AKS cluster.
+ */
+async function isAKSCluster (): Promise<Boolean> {
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: See https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html 

It's better to use `boolean` instead of `Boolean`.

File: src/components/kubectl/dashboard.ts [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+
+        if (!isAKSNode) {
+            return false;
+        }
+    }
+
+    return true;
+}
+
+function _isNodeAKS (node) : Boolean {
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: `Boolean` -> `boolean`

File: src/components/kubectl/dashboard.ts [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+    const name:string = node.metadata.name;
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: Leave an additional space between `name: string`

File: src/components/kubectl/dashboard.ts [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+    );
+    const resultsJson = JSON.parse(dashboardResults.stdout);
+    return resultsJson.items[0].metadata.name;
+}
+
+/**
+ * Stopgap to open the dashboard for AKS users. We port-forward directly
+ * to the kube-system dashboard pod instead of invoking `kubectl proxy`.
+ */
+async function openDashboardForAKSCluster () {
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: Add return type `: Promise<void>` at the end.

File: src/components/kubectl/port-forward.ts [hunk 5]
```diff
@@ -210,6 +212,10 @@ export async function portForwardToPod (podName: string, portMapping: PortMappin
         } as portFinder.PortFinderOptions);
     }
 
-    kubectl.invokeInTerminal(`port-forward ${podName} ${usedPort}:${targetPort}`);
+    let usedNamespace = namespace === undefined ? 'default' : namespace;
+
+    kubectl.invokeInTerminal(`port-forward ${podName} ${usedPort}:${targetPort} -n ${usedNamespace}`);
```
Comment (testforstephen) [inline src/components/kubectl/port-forward.ts]: `kubectl.invokeInTerminal` will run the command in the shared terminal by default. But port forwarding plays as a proxy server, and the terminal will be always occupied. In order not to affect other operations, could we run `port-forward` in a new Terminal?

File: src/components/kubectl/dashboard.ts [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+import { shell } from '../../shell';
+import { create as kubectlCreate, Kubectl } from '../../kubectl';
+
+
+const KUBE_DASHBOARD_URL = "http://localhost:8001/ui/";
+const TERMINAL_NAME = "Kubernetes Dashboard";
+const PROXY_OUTPUT_FILE = resolve(__dirname, 'proxy.out');
+
+const kubectl = kubectlCreate(host, fs, shell);
+const MAX_PORT_COUNT = 65535;
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: useless variable.

File: src/components/kubectl/port-forward.ts [hunk 7]
```diff
@@ -195,8 +195,10 @@ async function findPortForwardablePods () : Promise<PortForwardFindPodsResult> {
  * Invokes kubectl port-forward.
  * @param podName The pod name.
  * @param portMapping The PortMapping object. Provides the local and target ports.
+ * @param namespace  The namespace to use to find the pod in.
+ * @returns The locally bound port that was used.
  */
-export async function portForwardToPod (podName: string, portMapping: PortMapping) {
+export async function portForwardToPod (podName: string, portMapping: PortMapping, namespace?: string) : Promise<Number> {
```
Comment (testforstephen) [inline src/components/kubectl/port-forward.ts]: `Number` -> `number`.

File: src/components/kubectl/dashboard.ts [hunk 8]
```diff
@@ -0,0 +1,180 @@
...
+    } catch (e) {
+        console.log('Could not remove Kubernetes API Proxy stream');
+    }
+};
+
+/**
+ * Callback to read data written to the Kubernetes API Proxy output stream.
+ * @param data
+ */
+const onStreamData = (data:String) => {
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: `String` -> `string`

File: src/components/kubectl/dashboard.ts [hunk 9]
```diff
@@ -0,0 +1,180 @@
...
+        opn(`http://localhost:${boundPort}`);
+    }, 2500);
+    return;
+}
+
+/**
+ * Runs `kubectl proxy` in a terminal process spawned by the extension, and opens the Kubernetes
+ * dashboard in the user's preferred browser.
+ */
+export async function dashboardKubernetes ():Promise<void> {
```
Comment (testforstephen) [inline src/components/kubectl/dashboard.ts]: Leave a space between `(): Promise<void>`

**Comment by bnookala** [comment]
@testforstephen updated with the changes you requested.
