### PR TITLE
Better error messages if docker push fails during Run

### LINKED ISSUE #77: Kubernetes: Run failed with no further direction
Tried Kubernetes: Run and got the notification:
screen shot 2018-03-09 at 11 07 09 am

And here's the message in Output window:
screen shot 2018-03-09 at 11 06 10 am

It would be nice if we can provide further directions to resolve the problem. I could not tell the cause from the error message.

### PR DESCRIPTION
**Pull request by itowlson**
When `docker push` failed during a Kubernetes Run command, we would just say "Image push failed" and dump standard error.  The Docker error often did not help users to understand what the problem might be.  This PR checks for known messages and suggests possible remediations (e.g. user id not configured, user not logged in to Docker).

Fixes #77.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -721,9 +733,9 @@ function buildPushThenExec(fn) {
                         vscode.window.showInformationMessage(image + ' pushed.');
```
Comment (testforstephen) [inline src/extension.ts]: Before executing `push`, it's better to add user consent `This command needs to push your docker image to docker hub, do you want to continue?`

Comment (itowlson) [reply src/extension.ts]: Yeah, this has been raised as #80.  As noted there, this also gets us thinking about giving options for ACR etc., private registries and local registry (for minikube), and aligning with how vscode-docker handles this stuff.  Adding to the complexity, a consent prompt entails tracking that the user has consented so we don't bug them every time.  I'd like to restrict the scope of this PR to giving better errors in the existing failure cases, and tackle the broader issue of our interaction with registries in a subsequent one.

Comment (testforstephen) [reply src/extension.ts]: Ok to do it on the new PR.
